-- LexAgent AI — Faz 6 eklentisi: Mevzuat (ARTIK KULLANILMIYOR)
-- Bu dosya, statik/ornek veri setiyle calisan ilk mevzuat iskeletini olustruyordu.
-- Daha sonra canli arama (Gemini + google_search) ile degistirildi; bu SQL'i
-- CALISTIRMAYIN. Tabloyu kaldirmak icin supabase/007_mevzuat_canli.sql'i calistirin.
